#!/usr/bin/env node
// Builds the skills whose body is a doc in this repo, so the doc stays the single source
// (cbundy/dev-system#126). Each entry in SKILLS combines:
//   - source: the skill's frontmatter (no `version:`) and any skill-only text, with one
//     INCLUDE_MARKER line where the doc goes,
//   - doc: the markdown document; its top-level `# ` title is dropped (the source gives the
//     skill its own title) and every relative link becomes an absolute GitHub URL, because
//     a skill is read from the plugin cache, where repo paths do not exist,
// into output, with `version:` taken from the root package.json. scripts/release-bump.js sets
// that same version in every SKILL.md and package.json, so a released tree stays in sync
// without running this script.
//
//   node scripts/build-skills.js           write every output
//   node scripts/build-skills.js --check   exit 1 if any output is out of date (lint)
//
// Node built-ins only.
"use strict";

const fs = require("node:fs");
const path = require("node:path");

const REPO_ROOT = path.join(__dirname, "..");
const BLOB_BASE = "https://github.com/cbundy/dev-system/blob/main/";
const INCLUDE_MARKER = "<!-- include-doc -->";
const REGEN_COMMAND = "npm run build:skills";

// Paths are relative to the repo root.
const SKILLS = [
  {
    source: "plugins/callum-flow/skills/onboard/SKILL.src.md",
    doc: "docs/onboarding.md",
    output: "plugins/callum-flow/skills/onboard/SKILL.md",
  },
];

// Rewrites one link target found in `doc` (repo-relative path). Absolute URLs, mailto:,
// root-relative paths and same-page anchors are left alone.
function rewriteTarget(target, doc, root) {
  if (/^([a-z][a-z0-9+.-]*:|#|\/)/i.test(target)) return target;
  const hashAt = target.indexOf("#");
  const filePart = hashAt === -1 ? target : target.slice(0, hashAt);
  const anchor = hashAt === -1 ? "" : target.slice(hashAt);
  const repoPath = path.posix.normalize(path.posix.join(path.posix.dirname(doc), filePart));
  if (repoPath.startsWith("../")) {
    throw new Error(`${doc}: link '${target}' points outside the repo`);
  }
  if (!fs.existsSync(path.join(root, repoPath))) {
    throw new Error(`${doc}: link '${target}' points to '${repoPath}', which does not exist`);
  }
  return BLOB_BASE + repoPath.replace(/\/$/, "") + anchor;
}

// Rewrites inline links `[text](target "title")` and reference definitions
// `[label]: target`, outside fenced code blocks.
function rewriteLinks(markdown, doc, root) {
  let inFence = false;
  return markdown
    .split("\n")
    .map((line) => {
      if (/^\s*(```|~~~)/.test(line)) {
        inFence = !inFence;
        return line;
      }
      if (inFence) return line;
      const refDef = line.match(/^(\s{0,3}\[[^\]]+\]:\s*)(\S+)(.*)$/);
      if (refDef) return refDef[1] + rewriteTarget(refDef[2], doc, root) + refDef[3];
      return line.replace(/\]\(([^)\s]+)((?:\s+"[^"]*")?)\)/g, (_, target, title) =>
        `](${rewriteTarget(target, doc, root)}${title})`,
      );
    })
    .join("\n");
}

// Returns the generated SKILL.md text for one SKILLS entry.
function buildSkill(entry, { root = REPO_ROOT, version } = {}) {
  if (version === undefined) {
    version = JSON.parse(fs.readFileSync(path.join(root, "package.json"), "utf-8")).version;
  }
  const source = fs.readFileSync(path.join(root, entry.source), "utf-8");
  const fm = source.match(/^---\n([\s\S]*?)\n---\n/);
  if (!fm) throw new Error(`${entry.source}: no frontmatter block found`);
  if (/^version:/m.test(fm[1])) {
    throw new Error(`${entry.source}: drop the version: line; it comes from package.json`);
  }
  const body = source.slice(fm[0].length);
  const markers = body.split("\n").filter((l) => l.trim() === INCLUDE_MARKER).length;
  if (markers !== 1) {
    throw new Error(`${entry.source}: expected exactly one '${INCLUDE_MARKER}' line, found ${markers}`);
  }

  let doc = fs.readFileSync(path.join(root, entry.doc), "utf-8");
  doc = doc.replace(/^# [^\n]*\n+/, "");
  doc = rewriteLinks(doc, entry.doc, root).replace(/\n+$/, "");

  const notice =
    `<!-- GENERATED by scripts/build-skills.js from ${entry.source} and ${entry.doc}. ` +
    `Do not edit this file: edit those, then run \`${REGEN_COMMAND}\`. -->`;
  const filled = body
    .split("\n")
    .map((l) => (l.trim() === INCLUDE_MARKER ? doc : l))
    .join("\n")
    .replace(/^\n+/, "")
    .replace(/\n*$/, "\n");
  return `---\n${fm[1]}\nversion: ${version}\n---\n\n${notice}\n\n${filled}`;
}

// Writes (or, with check, compares) every output. Returns the list of stale outputs.
function run({ root = REPO_ROOT, skills = SKILLS, check = false, log = console.log } = {}) {
  const stale = [];
  for (const entry of skills) {
    const want = buildSkill(entry, { root });
    const outPath = path.join(root, entry.output);
    const have = fs.existsSync(outPath) ? fs.readFileSync(outPath, "utf-8") : null;
    if (have === want) continue;
    stale.push(entry.output);
    if (!check) {
      fs.mkdirSync(path.dirname(outPath), { recursive: true });
      fs.writeFileSync(outPath, want);
      log(`build-skills: wrote ${entry.output}`);
    }
  }
  return stale;
}

if (require.main === module) {
  const check = process.argv.includes("--check");
  try {
    const stale = run({ check });
    if (check && stale.length > 0) {
      for (const out of stale) console.error(`build-skills: ${out} is out of date`);
      console.error(`build-skills: run \`${REGEN_COMMAND}\` and commit the result`);
      process.exit(1);
    }
    if (check) console.log(`build-skills: ${SKILLS.length} generated skill(s) up to date`);
  } catch (err) {
    console.error(`build-skills: ${err.message}`);
    process.exit(1);
  }
}

module.exports = { SKILLS, INCLUDE_MARKER, BLOB_BASE, rewriteLinks, buildSkill, run };
